# Generated by Django 3.0 on 2020-02-24 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='job_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='post_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(default=0)),
                ('project_description', models.TextField(default=0)),
                ('category', models.TextField(default=0)),
                ('budget', models.IntegerField(default=0)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('ftech', models.TextField(default=0)),
                ('btech', models.TextField(default=0)),
                ('post_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='reviews_hirer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField(default=0)),
                ('hcomments', models.TextField(default=0)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payment_hirer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(default=0)),
                ('payment_amount', models.IntegerField(default=0)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hirer_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('company_name', models.TextField(default=0)),
                ('contact', models.IntegerField(default=0)),
                ('email', models.EmailField(default=0, max_length=254)),
                ('addres', models.TextField(default=0)),
                ('start_date', models.DateField()),
                ('pimage', models.ImageField(upload_to='')),
                ('status', models.IntegerField(default=0)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
