# Generated by Django 3.0 on 2020-02-24 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hirer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_job',
            name='userid',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='btech',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='category',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='ftech',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='project_description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='project_name',
            field=models.TextField(max_length=100),
        ),
    ]
