# Generated by Django 3.0 on 2020-02-26 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hirer', '0002_auto_20200224_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirer_profile',
            name='addres',
        ),
        migrations.AlterField(
            model_name='hirer_profile',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
