# Generated by Django 3.1.5 on 2021-03-07 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hirer', '0006_auto_20210307_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_job',
            name='userid',
        ),
        migrations.AddField(
            model_name='post_job',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
