# Generated by Django 3.1.5 on 2021-03-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirer', '0007_auto_20210307_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_job',
            old_name='user_id',
            new_name='userid',
        ),
    ]
