# Generated by Django 3.1.5 on 2021-03-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirer', '0008_auto_20210307_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_job',
            name='userid',
        ),
    ]
