# Generated by Django 3.1.5 on 2021-03-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirer', '0009_remove_post_job_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_job',
            name='btech',
        ),
        migrations.RemoveField(
            model_name='post_job',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='post_job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post_job',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='post_job',
            name='ftech',
        ),
        migrations.RemoveField(
            model_name='post_job',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='post_job',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='post_job',
            name='start_time',
        ),
    ]
