# Generated by Django 3.1.5 on 2021-03-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirer', '0010_auto_20210307_1514'),
        ('hirer', '0011_post_job_userid'),
    ]

    operations = [
    ]
