# Generated by Django 3.1.5 on 2021-03-07 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hirer', '0012_merge_20210307_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_job',
            name='btech',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='post_job',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post_job',
            name='category',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post_job',
            name='end_time',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='post_job',
            name='ftech',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='post_job',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post_job',
            name='project_description',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='post_job',
            name='start_time',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='project_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
