# Generated by Django 3.0 on 2020-02-12 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('Qualification', models.TextField()),
                ('tech_exp', models.TextField()),
                ('exp', models.TextField()),
                ('rate_hr', models.IntegerField()),
                ('jdate', models.DateField()),
                ('status', models.IntegerField()),
                ('acc_bal', models.IntegerField()),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='extendeduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin1', models.IntegerField()),
                ('is_user', models.IntegerField()),
                ('is_hirer', models.IntegerField()),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
