# Generated by Django 3.0.6 on 2020-06-15 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='is_admin1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='is_hirer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='is_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Qualification',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='acc_bal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='exp',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='jdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='rate_hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='tech_exp',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='reviews_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField(default=0)),
                ('hcomments', models.TextField(default='')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
