# Generated by Django 3.0.6 on 2020-06-17 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user1', '0003_remove_user_profile_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='userid',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
