# Generated by Django 3.0.6 on 2020-06-15 09:14

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects_bids',
            name='bid_date',
        ),
        migrations.AddField(
            model_name='projects_bids',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projects_bids',
            name='job_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects_bids',
            name='userid',
            field=models.ManyToManyField(default=0, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projects_bids',
            name='comments',
            field=models.TextField(default=0),
        ),
    ]
