# Generated by Django 3.0.6 on 2020-06-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_auto_20200615_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects_bids',
            name='userid',
        ),
    ]
