# Generated by Django 3.1.5 on 2021-03-07 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hirer', '0004_auto_20200302_2028'),
        ('admin1', '0004_auto_20200617_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects_bids',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirer.post_job'),
        ),
    ]
