# Generated by Django 3.1.5 on 2021-03-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0005_auto_20210307_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects_bids',
            name='userid',
        ),
    ]
