# Generated by Django 3.1.5 on 2021-03-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0007_projects_bids_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects_bids',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='projects_bids',
            name='userid',
        ),
    ]
