# Generated by Django 3.1.5 on 2021-03-07 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hirer', '0004_auto_20200302_2028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin1', '0008_auto_20210307_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects_bids',
            name='job_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hirer.post_job'),
        ),
        migrations.AddField(
            model_name='projects_bids',
            name='userid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
