# Generated by Django 3.1.5 on 2021-03-07 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hirer', '0013_auto_20210307_1705'),
        ('admin1', '0009_auto_20210307_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects_bids',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirer.post_job'),
        ),
    ]
