# Generated by Django 3.1.5 on 2021-03-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0010_auto_20210307_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects_bids',
            name='job_id',
            field=models.IntegerField(default=0),
        ),
    ]
